sector_map = {
    "ZENITHBANK": "Banking",
    "GTCO": "Banking",
    "ACCESSCORP": "Banking",
    "UBA": "Banking",
    "STANBIC": "Banking",
    "FBNH": "Banking",
    "MTNN": "Telecom",
    "BUACEMENT": "Industrial Goods",
    "DANGCEM": "Industrial Goods",
    "SEPLAT": "Oil & Gas",
    "NESTLE": "Consumer Goods",
    "NB": "Consumer Goods",
    "GUINNESS": "Consumer Goods",
    "WAPCO": "Industrial Goods",
    "FLOURMILL": "Consumer Goods",
    "DANGSUGAR": "Consumer Goods",
    "INTBREW": "Consumer Goods",
    "GEREGU": "Power",
    "ETI": "Banking",
    "PZ": "Consumer Goods",
    "CUSTODIAN": "Insurance",
    "UCAP": "Investment",
    "STERLINGNG": "Banking",
    "FIDELITYBK": "Banking",
    "TRANSCORP": "Conglomerates",
    "NASCON": "Consumer Goods",
    "CADBURY": "Consumer Goods",
    "UNILEVER": "Consumer Goods",
    "BERGER": "Industrial Goods",
    "OANDO": "Oil & Gas",
    "JAIZBANK": "Banking",
    "WEMABANK": "Banking",
    "UNITYBNK": "Banking",
    "AIICO": "Insurance",
    "SOVRENINS": "Insurance",
    "MANSARD": "Insurance",
    "NEM": "Insurance",
    "AFRIPRUD": "Investment",
    "HONYFLOUR": "Consumer Goods",
    "MAYBAKER": "Healthcare",
    "VITAFOAM": "Consumer Goods",
    "CHAMPION": "Consumer Goods",
    "IKEJAHOTEL": "Hospitality",
    "JOHNHOLT": "Conglomerates",
    "TIP": "Industrial Goods",
    "TRANSCORP HOTELS": "Hospitality",
    "UACN": "Conglomerates",
    "BUAFOODS": "Consumer Goods",
    "CORNERST": "Insurance",
    "LIVESTOCK": "Agriculture",
    "UPDCREIT": "REITs",
    "NAHCO": "Transport",
    "MCNICHOLS": "Consumer Goods",
    "ETERNA": "Oil & Gas",
    "FIDSON": "Healthcare",
    "FCMB": "Banking",
    "OKOMUOIL": "Agriculture",
    "CWG": "Technology",
    "PRESCO": "Agriculture"
}
