sector_map = {
    "ABBEYBDS": "Other",
    "ABCTRANS": "Other",
    "ACADEMY": "Other",
    "ACCESSCORP": "Banking",
    "AFRINSURE [MRF]": "Other",
    "AFRIPRUD": "Other",
    "AFROMEDIA [MRF]": "Other",
    "AIICO": "Insurance",
    "AIRTELAFRI": "Telecom",
    "ALEX": "Other",
    "ALEX [BLS]": "Other",
    "ARADEL": "Other",
    "ASOSAVINGS [DWL]": "Other",
    "AUSTINLAZ": "Other",
    "AUSTINLAZ [RST]": "Other",
    "AVAIF": "Other",
    "BAPLC": "Other",
    "BERGER": "Industrial Goods",
    "BETAGLAS": "Other",
    "BUACEMENT": "Industrial Goods",
    "BUAFOODS": "Other",
    "CADBURY": "Consumer Goods",
    "CAP": "Industrial Goods",
    "CAVERTON": "Other",
    "CHAMPION": "Consumer Goods",
    "CHAMPION [BLS]": "Other",
    "CHAMS": "Other",
    "CHELLARAM": "Other",
    "CILEASING": "Other",
    "CILEASING [MRF]": "Other",
    "CONHALLPLC": "Other",
    "CONOIL": "Oil & Gas",
    "CONOIL [MRF]": "Other",
    "CORNERST": "Insurance",
    "CORNERST [MRF]": "Other",
    "CUSTODIAN": "Other",
    "CUTIX": "Other",
    "CWG": "Other",
    "DAARCOMM": "Other",
    "DANGCEM": "Other",
    "DANGSUGAR": "Consumer Goods",
    "DEAPCAP": "Other",
    "DEAPCAP [DWL]": "Other",
    "DUNLOP [DIP]": "Other",
    "EKOCORP [DIP]": "Other",
    "ELLAHLAKES": "Other",
    "ENAMELWA": "Other",
    "ETERNA": "Oil & Gas",
    "ETI": "Other",
    "ETRANZACT": "Other",
    "EUNISELL": "Other",
    "FCMB": "Banking",
    "FGS202886": "Other",
    "FGSUK2033S6": "Other",
    "FIDELITYBK": "Banking",
    "FIDSON": "Other",
    "FIRSTHOLDCO": "Other",
    "FTGINSURE [DWL]": "Other",
    "FTNCOCOA": "Other",
    "FTNCOCOA [RST]": "Other",
    "GEREGU": "Other",
    "GOLDBREW": "Other",
    "GOLDBREW [BMF]": "Other",
    "GTCO": "Banking",
    "GUINEAINS": "Other",
    "GUINNESS": "Other",
    "HMCALL": "Other",
    "HONYFLOUR": "Other",
    "HONYFLOUR [BLS]": "Other",
    "IKEJAHOTEL": "Other",
    "IMG": "Other",
    "INFINITY": "Other",
    "INFINITY [BLS]": "Other",
    "INTBREW": "Other",
    "INTENEGINS": "Other",
    "INTENEGINS [MRS]": "Other",
    "JAIZBANK": "Banking",
    "JAIZBANK [MRF]": "Other",
    "JAPAULGOLD": "Other",
    "JBERGER": "Other",
    "JOHNHOLT": "Conglomerates",
    "JULI": "Other",
    "LASACO": "Insurance",
    "LEARNAFRCA": "Other",
    "LEGENDINT": "Other",
    "LEGENDINT [BLS]": "Other",
    "LINKASSURE": "Other",
    "LIVESTOCK": "Other",
    "LIVINGTRUST": "Other",
    "MANSARD": "Other",
    "MAYBAKER": "Other",
    "MBENEFIT": "Insurance",
    "MBENEFIT [MRF]": "Other",
    "MCNICHOLS": "Consumer Goods",
    "MECURE": "Other",
    "MEYER": "Other",
    "MORISON": "Other",
    "MORISON [MRF]": "Other",
    "MRS": "Oil & Gas",
    "MTNN": "Telecom",
    "MULTITREX [DWL]": "Other",
    "MULTIVERSE": "Other",
    "NAHCO": "Transport",
    "NASCON": "Other",
    "NB": "Consumer Goods",
    "NCR": "Other",
    "NEIMETH": "Other",
    "NEM": "Insurance",
    "NESTLE": "Consumer Goods",
    "NGXGROUP": "Exchange",
    "NIDF": "Other",
    "NNFM": "Other",
    "NOTORE": "Other",
    "NOTORE [BMF]": "Other",
    "NPFMCRFBK": "Other",
    "NSLTECH": "Other",
    "OANDO": "Oil & Gas",
    "OANDO [MRF]": "Other",
    "OKOMUOIL": "Agriculture",
    "OMATEK": "Other",
    "PHARMDEKO [MRF]": "Other",
    "PREMPAINTS [MRF]": "Other",
    "PRESCO": "Agriculture",
    "PRESTIGE": "Insurance",
    "PRESTIGE [BMF]": "Other",
    "PZ": "Other",
    "REDSTAREX": "Other",
    "REGALINS": "Insurance",
    "REGALINS [MRF]": "Other",
    "RONCHESS": "Other",
    "ROYALEX": "Insurance",
    "ROYALEX [MRF]": "Other",
    "RTBRISCOE": "Other",
    "SCOA": "Other",
    "SEPLAT": "Oil & Gas",
    "SFSREIT": "Other",
    "SKYAVN": "Other",
    "SMURFIT": "Other",
    "SMURFIT [MRF]": "Other",
    "SOVRENINS": "Insurance",
    "SOVRENINS [MRF]": "Other",
    "STACO [DWL]": "Other",
    "STANBIC": "Banking",
    "STDINSURE [DWL]": "Other",
    "STERLINGNG": "Banking",
    "STERLINGNG [MRF]": "Other",
    "SUNUASSUR": "Insurance",
    "TANTALIZER": "Other",
    "THOMASWY [MRS]": "Other",
    "TIP": "Other",
    "TOTAL": "Oil & Gas",
    "TRANSCOHOT": "Other",
    "TRANSCORP": "Conglomerates",
    "TRANSEXPR": "Other",
    "TRANSEXPR [MRF]": "Other",
    "TRANSPOWER": "Other",
    "TRIPPLEG": "Other",
    "UACN": "Conglomerates",
    "UBA": "Banking",
    "UCAP": "Investment",
    "UHOMREIT": "Other",
    "UNILEVER": "Consumer Goods",
    "UNIONDICON": "Other",
    "UNIONDICON [DWL]": "Other",
    "UNITYBNK [MRF]": "Banking",
    "UNIVINSURE": "Other",
    "UNIVINSURE [MRF]": "Other",
    "UPDC": "Other",
    "UPDC [BLS]": "Other",
    "UPDCREIT": "Other",
    "UPL": "Other",
    "VANLEER [DIP]": "Other",
    "VERITASKAP": "Other",
    "VFDGROUP": "Investment",
    "VITAFOAM": "Consumer Goods",
    "WAPCO": "Industrial Goods",
    "WAPIC": "Other",
    "WAPIC [MRF]": "Other",
    "WEMABANK": "Banking",
    "ZENITHBANK": "Banking",
}
